"""Agregando onupdate cascade en devices groups

Revision ID: b443d4197229
Revises: 13ac7a88a695
Create Date: 2025-07-06 16:41:34.415738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b443d4197229'
down_revision: Union[str, Sequence[str], None] = '13ac7a88a695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('device_groups_device_id_key'), 'device_groups', type_='unique')
    op.drop_constraint(op.f('device_groups_device_id_fkey'), 'device_groups', type_='foreignkey')
    op.create_foreign_key(None, 'device_groups', 'devices', ['device_id'], ['device_id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_groups', type_='foreignkey')
    op.create_foreign_key(op.f('device_groups_device_id_fkey'), 'device_groups', 'devices', ['device_id'], ['device_id'])
    op.create_unique_constraint(op.f('device_groups_device_id_key'), 'device_groups', ['device_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
